
#include <stddef.h> // macro offsetof()
#include "uiki:uikbase.h"
#include "uiki:uikobj.h"
#include "uiki:uikglobal.h"

void main()
{
  int v;

    printf("\nStructures Offsets\n\n\n");

    printf("UIKBase:\n");
    v = offsetof(struct UIKBase, Library); printf("  $%04.4lx\t%5.5ld  lb_Library\n",v,v);
    v = offsetof(struct UIKBase, Flags); printf("  $%04.4lx\t%5.5ld  lb_Flags\n",v,v);
    v = offsetof(struct UIKBase, UIKFlags); printf("  $%04.4lx\t%5.5ld  lb_UIKFlags\n",v,v);
    v = offsetof(struct UIKBase, SegList); printf("  $%04.4lx\t%5.5ld  lb_SegList\n",v,v);
    v = offsetof(struct UIKBase, RegisteredObjList); printf("  $%04.4lx\t%5.5ld  lb_RegisteredObjList\n",v,v);
    v = offsetof(struct UIKBase, RegisteredImaList); printf("  $%04.4lx\t%5.5ld  lb_RegisteredImaList\n",v,v);
    v = offsetof(struct UIKBase, RegObjSemaphore); printf("  $%04.4lx\t%5.5ld  lb_RegObjSemaphore\n",v,v);
    v = offsetof(struct UIKBase, RegImaSemaphore); printf("  $%04.4lx\t%5.5ld  lb_RegImaSemaphore\n",v,v);
    v = offsetof(struct UIKBase, UIKPrefs); printf("  $%04.4lx\t%5.5ld  lb_UIKPrefs\n",v,v);
    v = offsetof(struct UIKBase, PrefsSemaphore); printf("  $%04.4lx\t%5.5ld  lb_PrefsSemaphore\n",v,v);
    v = offsetof(struct UIKBase, DefaultFont); printf("  $%04.4lx\t%5.5ld  lb_DefaultFont\n",v,v);
    v = offsetof(struct UIKBase, KeySupp); printf("  $%04.4lx\t%5.5ld  lb_KeySupp\n",v,v);
    v = offsetof(struct UIKBase, DefaultScreen); printf("  $%04.4lx\t%5.5ld  lb_DefaultScreen\n",v,v);
    v = offsetof(struct UIKBase, DefaultFontAttr); printf("  $%04.4lx\t%5.5ld  lb_DefaultFontAttr\n",v,v);
    v = offsetof(struct UIKBase, VBlankInt); printf("  $%04.4lx\t%5.5ld  lb_VBlankInt\n",v,v);
    v = offsetof(struct UIKBase, Ticks); printf("  $%04.4lx\t%5.5ld  lb_Ticks\n",v,v);
    v = offsetof(struct UIKBase, ZonedUIK); printf("  $%04.4lx\t%5.5ld  lb_ZonedUIK\n",v,v);
    v = offsetof(struct UIKBase, OpenCount); printf("  $%04.4lx\t%5.5ld  lb_OpenCount\n",v,v);
    v = offsetof(struct UIKBase, padw); printf("  $%04.4lx\t%5.5ld  lb_padw\n",v,v);
    v = offsetof(struct UIKBase, LocaleBase); printf("  $%04.4lx\t%5.5ld  lb_LocaleBase\n",v,v);
    v = sizeof(struct UIKBase); printf("  $%04.4lx\t%5.5ld  UIKBase_SIZE\n\n",v,v);

    printf("UIKPrefs:\n");
    v = offsetof(struct UIKPrefs, Colors); printf("  $%04.4lx\t%5.5ld  uikp_Colors\n",v,v);
    v = offsetof(struct UIKPrefs, ColorTable); printf("  $%04.4lx\t%5.5ld  uikp_ColorTable\n",v,v);
    v = offsetof(struct UIKPrefs, PrefsFlags); printf("  $%04.4lx\t%5.5ld  uikp_PrefsFlags\n",v,v);
    v = offsetof(struct UIKPrefs, DefFontHeight); printf("  $%04.4lx\t%5.5ld  uikp_DefFontHeight\n",v,v);
    v = offsetof(struct UIKPrefs, DefFontName); printf("  $%04.4lx\t%5.5ld  uikp_DefFontName\n",v,v);
    v = offsetof(struct UIKPrefs, DefScreen_Depth); printf("  $%04.4lx\t%5.5ld  uikp_DefScreen_Depth\n",v,v);
    v = offsetof(struct UIKPrefs, DefScreen_ModeId); printf("  $%04.4lx\t%5.5ld  uikp_DefScreen_ModeId\n",v,v);
    v = offsetof(struct UIKPrefs, DefScreen_Modes); printf("  $%04.4lx\t%5.5ld  uikp_DefScreen_Modes\n",v,v);
    v = offsetof(struct UIKPrefs, DefScreen_Width); printf("  $%04.4lx\t%5.5ld  uikp_DefScreen_Width\n",v,v);
    v = offsetof(struct UIKPrefs, DefScreen_Height); printf("  $%04.4lx\t%5.5ld  uikp_DefScreen_Height\n",v,v);
    v = offsetof(struct UIKPrefs, InputMode); printf("  $%04.4lx\t%5.5ld  uikp_InputMode\n",v,v);
    v = offsetof(struct UIKPrefs, InputHeld); printf("  $%04.4lx\t%5.5ld  uikp_InputHeld\n",v,v);
    v = offsetof(struct UIKPrefs, InputAuto); printf("  $%04.4lx\t%5.5ld  uikp_InputAuto\n",v,v);
    v = offsetof(struct UIKPrefs, ZoneThick); printf("  $%04.4lx\t%5.5ld  uikp_ZoneThick\n",v,v);
    v = offsetof(struct UIKPrefs, ZoneSpeed); printf("  $%04.4lx\t%5.5ld  uikp_ZoneSpeed\n",v,v);
    v = offsetof(struct UIKPrefs, ValidTime); printf("  $%04.4lx\t%5.5ld  uikp_ValidTime\n",v,v);
    v = offsetof(struct UIKPrefs, WaitTime); printf("  $%04.4lx\t%5.5ld  uikp_WaitTime\n",v,v);
    v = offsetof(struct UIKPrefs, InputFlags); printf("  $%04.4lx\t%5.5ld  uikp_InputFlags\n",v,v);
    v = sizeof(struct UIKPrefs); printf("  $%04.4lx\t%5.5ld  UIKPrefs_SIZE\n\n",v,v);

    printf("UIKGlobal:\n");
    v = offsetof(struct UIKGlobal, Obj); printf("  $%04.4lx\t%5.5ld  uike_Obj\n",v,v);
    v = offsetof(struct UIKGlobal, UPort); printf("  $%04.4lx\t%5.5ld  uike_UPort\n",v,v);
    v = offsetof(struct UIKGlobal, Task); printf("  $%04.4lx\t%5.5ld  uike_Task\n",v,v);
    v = offsetof(struct UIKGlobal, Flags); printf("  $%04.4lx\t%5.5ld  uike_Flags\n",v,v);
    v = offsetof(struct UIKGlobal, RemObj); printf("  $%04.4lx\t%5.5ld  uike_RemObj\n",v,v);
    v = offsetof(struct UIKGlobal, Exable); printf("  $%04.4lx\t%5.5ld  uike_Exable\n",v,v);
    v = offsetof(struct UIKGlobal, ActiveSigBit); printf("  $%04.4lx\t%5.5ld  uike_ActiveSigBit\n",v,v);
    v = offsetof(struct UIKGlobal, ActiveMask); printf("  $%04.4lx\t%5.5ld  uike_ActiveMask\n",v,v);
    v = offsetof(struct UIKGlobal, SigBit); printf("  $%04.4lx\t%5.5ld  uike_SigBit\n",v,v);
    v = offsetof(struct UIKGlobal, SigMask); printf("  $%04.4lx\t%5.5ld  uike_SigMask\n",v,v);
    v = offsetof(struct UIKGlobal, CmdMask); printf("  $%04.4lx\t%5.5ld  uike_CmdMask\n",v,v);
    v = offsetof(struct UIKGlobal, ExcMask); printf("  $%04.4lx\t%5.5ld  uike_ExcMask\n",v,v);
    v = offsetof(struct UIKGlobal, ExtMask); printf("  $%04.4lx\t%5.5ld  uike_ExtMask\n",v,v);
    v = offsetof(struct UIKGlobal, WindowNum); printf("  $%04.4lx\t%5.5ld  uike_WindowNum\n",v,v);
    v = offsetof(struct UIKGlobal, ActiveObj); printf("  $%04.4lx\t%5.5ld  uike_ActiveObj\n",v,v);
    v = offsetof(struct UIKGlobal, StopVector); printf("  $%04.4lx\t%5.5ld  uike_StopVector\n",v,v);
    v = offsetof(struct UIKGlobal, RemoveVector); printf("  $%04.4lx\t%5.5ld  uike_RemoveVector\n",v,v);
    v = offsetof(struct UIKGlobal, OldLangEnglish); printf("  $%04.4lx\t%5.5ld  uike_OldLangEnglish\n",v,v);
    v = offsetof(struct UIKGlobal, OldLangOther); printf("  $%04.4lx\t%5.5ld  uike_OldLangOther\n",v,v);
    v = offsetof(struct UIKGlobal, OldLangage); printf("  $%04.4lx\t%5.5ld  uike_OldLangage\n",v,v);
    v = offsetof(struct UIKGlobal, IntuiMsg); printf("  $%04.4lx\t%5.5ld  uike_IntuiMsg\n",v,v);
    v = offsetof(struct UIKGlobal, IMSList); printf("  $%04.4lx\t%5.5ld  uike_IMSList\n",v,v);
    v = offsetof(struct UIKGlobal, CmdPort); printf("  $%04.4lx\t%5.5ld  uike_CmdPort\n",v,v);
    v = offsetof(struct UIKGlobal, CmdReq); printf("  $%04.4lx\t%5.5ld  uike_CmdReq\n",v,v);
    v = offsetof(struct UIKGlobal, IMDirec); printf("  $%04.4lx\t%5.5ld  uike_IMDirec\n",v,v);
    v = offsetof(struct UIKGlobal, IMCranP); printf("  $%04.4lx\t%5.5ld  uike_IMCranP\n",v,v);
    v = offsetof(struct UIKGlobal, KeySupp); printf("  $%04.4lx\t%5.5ld  uike_KeySupp\n",v,v);
    v = offsetof(struct UIKGlobal, ActiveKeyTank); printf("  $%04.4lx\t%5.5ld  uike_ActiveKeyTank\n",v,v);
    v = offsetof(struct UIKGlobal, Tmp); printf("  $%04.4lx\t%5.5ld  uike_Tmp\n",v,v);
    v = offsetof(struct UIKGlobal, OILBM); printf("  $%04.4lx\t%5.5ld  uike_OILBM\n",v,v);
    v = offsetof(struct UIKGlobal, O8SVX); printf("  $%04.4lx\t%5.5ld  uike_O8SVX\n",v,v);
    v = offsetof(struct UIKGlobal, padl); printf("  $%04.4lx\t%5.5ld  uike_padl\n",v,v);
    v = offsetof(struct UIKGlobal, InputMode); printf("  $%04.4lx\t%5.5ld  uike_InputMode\n",v,v);
    v = offsetof(struct UIKGlobal, InputHeld); printf("  $%04.4lx\t%5.5ld  uike_InputHeld\n",v,v);
    v = offsetof(struct UIKGlobal, InputAuto); printf("  $%04.4lx\t%5.5ld  uike_InputAuto\n",v,v);
    v = offsetof(struct UIKGlobal, padb); printf("  $%04.4lx\t%5.5ld  uike_padb\n",v,v);
    v = offsetof(struct UIKGlobal, ZoneListBase); printf("  $%04.4lx\t%5.5ld  uike_ZoneListBase\n",v,v);
    v = offsetof(struct UIKGlobal, ActiveZoneList); printf("  $%04.4lx\t%5.5ld  uike_ActiveZoneList\n",v,v);
    v = offsetof(struct UIKGlobal, ZoneRPort); printf("  $%04.4lx\t%5.5ld  uike_ZoneRPort\n",v,v);
    v = offsetof(struct UIKGlobal, ZonePlanes); printf("  $%04.4lx\t%5.5ld  uike_ZonePlanes\n",v,v);
    v = offsetof(struct UIKGlobal, InputFlags); printf("  $%04.4lx\t%5.5ld  uike_InputFlags\n",v,v);
    v = offsetof(struct UIKGlobal, TempoSpeed); printf("  $%04.4lx\t%5.5ld  uike_TempoSpeed\n",v,v);
    v = offsetof(struct UIKGlobal, JoyVal); printf("  $%04.4lx\t%5.5ld  uike_JoyVal\n",v,v);
    v = offsetof(struct UIKGlobal, OldJoyVal); printf("  $%04.4lx\t%5.5ld  uike_OldJoyVal\n",v,v);
    v = offsetof(struct UIKGlobal, JoyButs); printf("  $%04.4lx\t%5.5ld  uike_JoyButs\n",v,v);
    v = offsetof(struct UIKGlobal, OldJoyButs); printf("  $%04.4lx\t%5.5ld  uike_OldJoyButs\n",v,v);
    v = offsetof(struct UIKGlobal, DirButs); printf("  $%04.4lx\t%5.5ld  uike_DirButs\n",v,v);
    v = offsetof(struct UIKGlobal, ProcButs); printf("  $%04.4lx\t%5.5ld  uike_ProcButs\n",v,v);
    v = offsetof(struct UIKGlobal, IptButs); printf("  $%04.4lx\t%5.5ld  uike_IptButs\n",v,v);
    v = offsetof(struct UIKGlobal, IptChgs); printf("  $%04.4lx\t%5.5ld  uike_IptChgs\n",v,v);
    v = offsetof(struct UIKGlobal, TempoValidRight); printf("  $%04.4lx\t%5.5ld  uike_TempoValidRight\n",v,v);
    v = offsetof(struct UIKGlobal, TempoWaitRight); printf("  $%04.4lx\t%5.5ld  uike_TempoWaitRight\n",v,v);
    v = offsetof(struct UIKGlobal, TempoValidLeft); printf("  $%04.4lx\t%5.5ld  uike_TempoValidLeft\n",v,v);
    v = offsetof(struct UIKGlobal, TempoWaitLeft); printf("  $%04.4lx\t%5.5ld  uike_TempoWaitLeft\n",v,v);
    v = offsetof(struct UIKGlobal, TempoValidBack); printf("  $%04.4lx\t%5.5ld  uike_TempoValidBack\n",v,v);
    v = offsetof(struct UIKGlobal, TempoWaitBack); printf("  $%04.4lx\t%5.5ld  uike_TempoWaitBack\n",v,v);
    v = offsetof(struct UIKGlobal, TempoValidForw); printf("  $%04.4lx\t%5.5ld  uike_TempoValidForw\n",v,v);
    v = offsetof(struct UIKGlobal, TempoWaitForw); printf("  $%04.4lx\t%5.5ld  uike_TempoWaitForw\n",v,v);
    v = offsetof(struct UIKGlobal, TempoValidFire); printf("  $%04.4lx\t%5.5ld  uike_TempoValidFire\n",v,v);
    v = offsetof(struct UIKGlobal, TempoWaitFire); printf("  $%04.4lx\t%5.5ld  uike_TempoWaitFire\n",v,v);
    v = offsetof(struct UIKGlobal, JoyEvents); printf("  $%04.4lx\t%5.5ld  uike_JoyEvents\n",v,v);
    v = offsetof(struct UIKGlobal, JTBeg); printf("  $%04.4lx\t%5.5ld  uike_JTBeg\n",v,v);
    v = offsetof(struct UIKGlobal, JTEnd); printf("  $%04.4lx\t%5.5ld  uike_JTEnd\n",v,v);
    v = offsetof(struct UIKGlobal, InputVector); printf("  $%04.4lx\t%5.5ld  uike_InputVector\n",v,v);
    v = offsetof(struct UIKGlobal, InputMainVector); printf("  $%04.4lx\t%5.5ld  uike_InputMainVector\n",v,v);
    v = offsetof(struct UIKGlobal, Locale); printf("  $%04.4lx\t%5.5ld  uike_Locale\n",v,v);
    v = sizeof(struct UIKGlobal); printf("  $%04.4lx\t%5.5ld  UIKGLOBAL_SIZE\n\n",v,v);

    printf("UIKObj:\n");
    v = offsetof(struct UIKObj, List); printf("  $%04.4lx\t%5.5ld  uo_List\n",v,v);
    v = offsetof(struct UIKObj, Link); printf("  $%04.4lx\t%5.5ld  uo_Link\n",v,v);
    v = offsetof(struct UIKObj, Hook); printf("  $%04.4lx\t%5.5ld  uo_Hook\n",v,v);
    v = offsetof(struct UIKObj, UIK); printf("  $%04.4lx\t%5.5ld  uo_UIK\n",v,v);
    v = offsetof(struct UIKObj, sc); printf("  $%04.4lx\t%5.5ld  uo_sc\n",v,v);
    v = offsetof(struct UIKObj, w); printf("  $%04.4lx\t%5.5ld  uo_w\n",v,v);
    v = offsetof(struct UIKObj, rq); printf("  $%04.4lx\t%5.5ld  uo_rq\n",v,v);
    v = offsetof(struct UIKObj, rp); printf("  $%04.4lx\t%5.5ld  uo_rp\n",v,v);
    v = offsetof(struct UIKObj, Box); printf("  $%04.4lx\t%5.5ld  uo_Box\n",v,v);
    v = offsetof(struct UIKObj, UserULong1); printf("  $%04.4lx\t%5.5ld  uo_UserULong1\n",v,v);
    v = offsetof(struct UIKObj, UserULong2); printf("  $%04.4lx\t%5.5ld  uo_UserULong2\n",v,v);
    v = offsetof(struct UIKObj, Status); printf("  $%04.4lx\t%5.5ld  uo_Status\n",v,v);
    v = offsetof(struct UIKObj, MouseIn); printf("  $%04.4lx\t%5.5ld  uo_MouseIn\n",v,v);
    v = offsetof(struct UIKObj, MouseX); printf("  $%04.4lx\t%5.5ld  uo_MouseX\n",v,v);
    v = offsetof(struct UIKObj, MouseY); printf("  $%04.4lx\t%5.5ld  uo_MouseY\n",v,v);
    v = offsetof(struct UIKObj, RegisterId); printf("  $%04.4lx\t%5.5ld  uo_RegisterId\n",v,v);
    v = offsetof(struct UIKObj, Icon); printf("  $%04.4lx\t%5.5ld  uo_Icon\n",v,v);
    v = offsetof(struct UIKObj, Parent); printf("  $%04.4lx\t%5.5ld  uo_Parent\n",v,v);
    v = offsetof(struct UIKObj, Flags); printf("  $%04.4lx\t%5.5ld  uo_Flags\n",v,v);
    v = offsetof(struct UIKObj, TitleFlags); printf("  $%04.4lx\t%5.5ld  uo_TitleFlags\n",v,v);
    v = offsetof(struct UIKObj, ResizeFlags); printf("  $%04.4lx\t%5.5ld  uo_ResizeFlags\n",v,v);
    v = offsetof(struct UIKObj, ActBoxPen); printf("  $%04.4lx\t%5.5ld  uo_ActBoxPen\n",v,v);
    v = offsetof(struct UIKObj, InactBoxPen); printf("  $%04.4lx\t%5.5ld  uo_InactBoxPen\n",v,v);
    v = offsetof(struct UIKObj, ActTitlePen); printf("  $%04.4lx\t%5.5ld  uo_ActTitlePen\n",v,v);
    v = offsetof(struct UIKObj, InactTitlePen); printf("  $%04.4lx\t%5.5ld  uo_InactTitlePen\n",v,v);
    v = offsetof(struct UIKObj, BoxPen); printf("  $%04.4lx\t%5.5ld  uo_BoxPen\n",v,v);
    v = offsetof(struct UIKObj, TitlePen); printf("  $%04.4lx\t%5.5ld  uo_TitlePen\n",v,v);
    v = offsetof(struct UIKObj, Id); printf("  $%04.4lx\t%5.5ld  uo_Id\n",v,v);
    v = offsetof(struct UIKObj, Title); printf("  $%04.4lx\t%5.5ld  uo_Title\n",v,v);
    v = offsetof(struct UIKObj, AltTitle); printf("  $%04.4lx\t%5.5ld  uo_AltTitle\n",v,v);
    v = offsetof(struct UIKObj, Automate); printf("  $%04.4lx\t%5.5ld  uo_Automate\n",v,v);
    v = offsetof(struct UIKObj, AltAutomate); printf("  $%04.4lx\t%5.5ld  uo_AltAutomate\n",v,v);
    v = offsetof(struct UIKObj, StartVector); printf("  $%04.4lx\t%5.5ld  uo_StartVector\n",v,v);
    v = offsetof(struct UIKObj, StopVector); printf("  $%04.4lx\t%5.5ld  uo_StopVector\n",v,v);
    v = offsetof(struct UIKObj, RemoveVector); printf("  $%04.4lx\t%5.5ld  uo_RemoveVector\n",v,v);
    v = offsetof(struct UIKObj, RefreshVector); printf("  $%04.4lx\t%5.5ld  uo_RefreshVector\n",v,v);
    v = offsetof(struct UIKObj, ResizeVector); printf("  $%04.4lx\t%5.5ld  uo_ResizeVector\n",v,v);
    v = offsetof(struct UIKObj, ExceptActVector); printf("  $%04.4lx\t%5.5ld  uo_ExceptActVector\n",v,v);
    v = offsetof(struct UIKObj, ExceptInaVector); printf("  $%04.4lx\t%5.5ld  uo_ExceptInaVector\n",v,v);
    v = offsetof(struct UIKObj, ExceptMovVector); printf("  $%04.4lx\t%5.5ld  uo_ExceptMovVector\n",v,v);
    v = offsetof(struct UIKObj, ExceptKeyVector); printf("  $%04.4lx\t%5.5ld  uo_ExceptKeyVector\n",v,v);
    v = offsetof(struct UIKObj, StartAfterVector); printf("  $%04.4lx\t%5.5ld  uo_StartAfterVector\n",v,v);
    v = offsetof(struct UIKObj, SelectVector); printf("  $%04.4lx\t%5.5ld  uo_SelectVector\n",v,v);
    v = offsetof(struct UIKObj, ExtentedVectors); printf("  $%04.4lx\t%5.5ld  uo_ExtentedVectors\n",v,v);
    v = offsetof(struct UIKObj, GermTagList); printf("  $%04.4lx\t%5.5ld  uo_GermTagList\n",v,v);
    v = offsetof(struct UIKObj, MinWidth); printf("  $%04.4lx\t%5.5ld  uo_MinWidth\n",v,v);
    v = offsetof(struct UIKObj, MinHeight); printf("  $%04.4lx\t%5.5ld  uo_MinHeight\n",v,v);
    v = offsetof(struct UIKObj, SigSemaphore); printf("  $%04.4lx\t%5.5ld  uo_SigSemaphore\n",v,v);
    v = offsetof(struct UIKObj, irp); printf("  $%04.4lx\t%5.5ld  uo_irp\n",v,v);
    v = offsetof(struct UIKObj, Region); printf("  $%04.4lx\t%5.5ld  uo_Region\n",v,v);
    v = offsetof(struct UIKObj, SpareRegion); printf("  $%04.4lx\t%5.5ld  uo_SpareRegion\n",v,v);
    v = offsetof(struct UIKObj, ClipCount); printf("  $%04.4lx\t%5.5ld  uo_ClipCount\n",v,v);
    v = offsetof(struct UIKObj, PatternPower); printf("  $%04.4lx\t%5.5ld  uo_PatternPower\n",v,v);
    v = offsetof(struct UIKObj, EraseColor); printf("  $%04.4lx\t%5.5ld  uo_EraseColor\n",v,v);
    v = offsetof(struct UIKObj, AutoRatio); printf("  $%04.4lx\t%5.5ld  uo_AutoRatio\n",v,v);
    v = offsetof(struct UIKObj, RegGerm); printf("  $%04.4lx\t%5.5ld  uo_RegGerm\n",v,v);
    v = offsetof(struct UIKObj, Pattern); printf("  $%04.4lx\t%5.5ld  uo_Pattern\n",v,v);
    v = offsetof(struct UIKObj, XAspect); printf("  $%04.4lx\t%5.5ld  uo_XAspect\n",v,v);
    v = offsetof(struct UIKObj, YAspect); printf("  $%04.4lx\t%5.5ld  uo_YAspect\n",v,v);
    v = offsetof(struct UIKObj, ObjExt); printf("  $%04.4lx\t%5.5ld  uo_ObjExt\n",v,v);
    v = sizeof(struct UIKObj); printf("  $%04.4lx\t%5.5ld  UIKOBJ_SIZE\n\n",v,v);

    printf("UIKObjStrGad:\n");
    v = offsetof(struct UIKObjStrGad, Obj); printf("  $%04.4lx\t%5.5ld  uos_Obj\n",v,v);
    v = offsetof(struct UIKObjStrGad, Gad); printf("  $%04.4lx\t%5.5ld  uos_Gad\n",v,v);
    v = offsetof(struct UIKObjStrGad, Buffer); printf("  $%04.4lx\t%5.5ld  uos_Buffer\n",v,v);
    v = offsetof(struct UIKObjStrGad, UndoBuffer); printf("  $%04.4lx\t%5.5ld  uos_UndoBuffer\n",v,v);
    v = offsetof(struct UIKObjStrGad, IntuiMsg); printf("  $%04.4lx\t%5.5ld  uos_IntuiMsg\n",v,v);
    v = offsetof(struct UIKObjStrGad, Reserved2); printf("  $%04.4lx\t%5.5ld  uos_Reserved2\n",v,v);
    v = offsetof(struct UIKObjStrGad, StrFlags); printf("  $%04.4lx\t%5.5ld  uos_StrFlags\n",v,v);
    v = offsetof(struct UIKObjStrGad, NumChars); printf("  $%04.4lx\t%5.5ld  uos_NumChars\n",v,v);
    v = offsetof(struct UIKObjStrGad, CursorPos); printf("  $%04.4lx\t%5.5ld  uos_CursorPos\n",v,v);
    v = offsetof(struct UIKObjStrGad, CharOffset); printf("  $%04.4lx\t%5.5ld  uos_CharOffset\n",v,v);
    v = offsetof(struct UIKObjStrGad, YOffset); printf("  $%04.4lx\t%5.5ld  uos_YOffset\n",v,v);
    v = offsetof(struct UIKObjStrGad, ActTextPen); printf("  $%04.4lx\t%5.5ld  uos_ActTextPen\n",v,v);
    v = offsetof(struct UIKObjStrGad, InactTextPen); printf("  $%04.4lx\t%5.5ld  uos_InactTextPen\n",v,v);
    v = offsetof(struct UIKObjStrGad, ActBgPen); printf("  $%04.4lx\t%5.5ld  uos_ActBgPen\n",v,v);
    v = offsetof(struct UIKObjStrGad, InactBgPen); printf("  $%04.4lx\t%5.5ld  uos_InactBgPen\n",v,v);
    v = offsetof(struct UIKObjStrGad, UserHook); printf("  $%04.4lx\t%5.5ld  uos_UserHook\n",v,v);
    v = offsetof(struct UIKObjStrGad, LongIntResult); printf("  $%04.4lx\t%5.5ld  uos_LongIntResult\n",v,v);
    v = offsetof(struct UIKObjStrGad, MaxChars); printf("  $%04.4lx\t%5.5ld  uos_MaxChars\n",v,v);
    v = offsetof(struct UIKObjStrGad, Reserved3); printf("  $%04.4lx\t%5.5ld  uos_IntuiMsg\n",v,v);
    v = offsetof(struct UIKObjStrGad, Reserved4); printf("  $%04.4lx\t%5.5ld  uos_Reserved2\n",v,v);
    v = sizeof(struct UIKObjStrGad); printf("  $%04.4lx\t%5.5ld  UIKObjStrGad_SIZE\n\n",v,v);

    printf("UIKObjPropGad:\n");
    v = offsetof(struct UIKObjPropGad, Obj); printf("  $%04.4lx\t%5.5ld  uop_Obj\n",v,v);
    v = offsetof(struct UIKObjPropGad, Gad); printf("  $%04.4lx\t%5.5ld  uop_Gad\n",v,v);
    v = offsetof(struct UIKObjPropGad, MouseStart); printf("  $%04.4lx\t%5.5ld  uop_MouseStart\n",v,v);
    v = offsetof(struct UIKObjPropGad, KnobOffs); printf("  $%04.4lx\t%5.5ld  uop_KnobOffs\n",v,v);
    v = offsetof(struct UIKObjPropGad, KnobWidth); printf("  $%04.4lx\t%5.5ld  uop_KnobWidth\n",v,v);
    v = offsetof(struct UIKObjPropGad, ContWidth); printf("  $%04.4lx\t%5.5ld  uop_ContWidth\n",v,v);
    v = offsetof(struct UIKObjPropGad, VisPC); printf("  $%04.4lx\t%5.5ld  uop_VisPC\n",v,v);
    v = offsetof(struct UIKObjPropGad, OffPC); printf("  $%04.4lx\t%5.5ld  uop_OffPC\n",v,v);
    v = offsetof(struct UIKObjPropGad, Ver); printf("  $%04.4lx\t%5.5ld  uop_Ver\n",v,v);
    v = offsetof(struct UIKObjPropGad, Moving); printf("  $%04.4lx\t%5.5ld  uop_Moving\n",v,v);
    v = offsetof(struct UIKObjPropGad, Tot); printf("  $%04.4lx\t%5.5ld  uop_Tot\n",v,v);
    v = offsetof(struct UIKObjPropGad, Vis); printf("  $%04.4lx\t%5.5ld  uop_Vis\n",v,v);
    v = offsetof(struct UIKObjPropGad, Pos); printf("  $%04.4lx\t%5.5ld  uop_Pos\n",v,v);
    v = offsetof(struct UIKObjPropGad, SaveKnob); printf("  $%04.4lx\t%5.5ld  uop_SaveKnob\n",v,v);
    v = offsetof(struct UIKObjPropGad, KnobAutomate); printf("  $%04.4lx\t%5.5ld  uop_KnobAutomate\n",v,v);
    v = offsetof(struct UIKObjPropGad, KnobNorAutomate); printf("  $%04.4lx\t%5.5ld  uop_KnobNorAutomate\n",v,v);
    v = offsetof(struct UIKObjPropGad, KnobAltAutomate); printf("  $%04.4lx\t%5.5ld  uop_KnobAltAutomate\n",v,v);
    v = sizeof(struct UIKObjPropGad); printf("  $%04.4lx\t%5.5ld  UIKObjPropGad_SIZE\n\n",v,v);

    printf("UIKObjWindow:\n");
    v = offsetof(struct UIKObjWindow, Obj); printf("  $%04.4lx\t%5.5ld  uow_Obj\n",v,v);
    v = offsetof(struct UIKObjWindow, NW); printf("  $%04.4lx\t%5.5ld  uow_NW\n",v,v);
    v = offsetof(struct UIKObjWindow, TitleBox); printf("  $%04.4lx\t%5.5ld  uow_TitleBox\n",v,v);
    v = offsetof(struct UIKObjWindow, UniconW); printf("  $%04.4lx\t%5.5ld  uow_UniconW\n",v,v);
    v = offsetof(struct UIKObjWindow, WinFlags); printf("  $%04.4lx\t%5.5ld  uow_WinFlags\n",v,v);
    v = offsetof(struct UIKObjWindow, IconLeftTop); printf("  $%04.4lx\t%5.5ld  uow_IconLeftTop\n",v,v);
    v = offsetof(struct UIKObjWindow, WFont); printf("  $%04.4lx\t%5.5ld  uow_WFont\n",v,v);
    v = offsetof(struct UIKObjWindow, TopBorderHeight); printf("  $%04.4lx\t%5.5ld  uow_TopBorderHeight\n",v,v);
    v = offsetof(struct UIKObjWindow, BottomBorderHeight); printf("  $%04.4lx\t%5.5ld  uow_BottomBorderHeight\n",v,v);
    v = offsetof(struct UIKObjWindow, LeftBorderWidth); printf("  $%04.4lx\t%5.5ld  uow_LeftBorderWidth\n",v,v);
    v = offsetof(struct UIKObjWindow, RightBorderWidth); printf("  $%04.4lx\t%5.5ld  uow_RightBorderWidth\n",v,v);
    v = offsetof(struct UIKObjWindow, OldLeft); printf("  $%04.4lx\t%5.5ld  uow_OldLeft\n",v,v);
    v = offsetof(struct UIKObjWindow, OldTop); printf("  $%04.4lx\t%5.5ld  uow_OldTop\n",v,v);
    v = offsetof(struct UIKObjWindow, OldWidth); printf("  $%04.4lx\t%5.5ld  uow_OldWidth\n",v,v);
    v = offsetof(struct UIKObjWindow, OldHeight); printf("  $%04.4lx\t%5.5ld  uow_OldHeight\n",v,v);
    v = offsetof(struct UIKObjWindow, CustomBitMap); printf("  $%04.4lx\t%5.5ld  uow_CustomBitMap\n",v,v);
    v = offsetof(struct UIKObjWindow, CustomAltBitMap); printf("  $%04.4lx\t%5.5ld  uow_CustomAltBitMap\n",v,v);
    v = offsetof(struct UIKObjWindow, WMenu); printf("  $%04.4lx\t%5.5ld  uow_WMenu\n",v,v);
    v = offsetof(struct UIKObjWindow, IconColors); printf("  $%04.4lx\t%5.5ld  uow_IconColors\n",v,v);
    v = offsetof(struct UIKObjWindow, GadgetList); printf("  $%04.4lx\t%5.5ld  uow_GadgetList\n",v,v);
    v = sizeof(struct UIKObjWindow); printf("  $%04.4lx\t%5.5ld  UIKOBJWINDOW_SIZE\n\n",v,v);

    printf("UIKObjList:\n");
    v = offsetof(struct UIKObjList, Obj); printf("  $%04.4lx\t%5.5ld  uol_Obj\n",v,v);
    v = offsetof(struct UIKObjList, Gad); printf("  $%04.4lx\t%5.5ld  uol_Gad\n",v,v);
    v = offsetof(struct UIKObjList, Vis); printf("  $%04.4lx\t%5.5ld  uol_Vis\n",v,v);
    v = offsetof(struct UIKObjList, Pos); printf("  $%04.4lx\t%5.5ld  uol_Pos\n",v,v);
    v = offsetof(struct UIKObjList, Max); printf("  $%04.4lx\t%5.5ld  uol_Max\n",v,v);
    v = offsetof(struct UIKObjList, Sel); printf("  $%04.4lx\t%5.5ld  uol_Sel\n",v,v);
    v = offsetof(struct UIKObjList, ListPen); printf("  $%04.4lx\t%5.5ld  uol_ListPen\n",v,v);
    v = offsetof(struct UIKObjList, SelectPen); printf("  $%04.4lx\t%5.5ld  uol_SelectPen\n",v,v);
    v = offsetof(struct UIKObjList, SelectTextPen); printf("  $%04.4lx\t%5.5ld  uol_SelectTextPen\n",v,v);
    v = offsetof(struct UIKObjList, Pad); printf("  $%04.4lx\t%5.5ld  uol_Pad\n",v,v);
    v = offsetof(struct UIKObjList, FeedBack); printf("  $%04.4lx\t%5.5ld  uol_FeedBack\n",v,v);
    v = offsetof(struct UIKObjList, ListFlags); printf("  $%04.4lx\t%5.5ld  uol_ListFlags\n",v,v);
    v = offsetof(struct UIKObjList, ListText); printf("  $%04.4lx\t%5.5ld  uol_ListText\n",v,v);
    v = offsetof(struct UIKObjList, SortFunc); printf("  $%04.4lx\t%5.5ld  uol_SortFunc\n",v,v);
    v = sizeof(struct UIKObjList); printf("  $%04.4lx\t%5.5ld  UIKOBJLIST_SIZE\n\n",v,v);
    /*
    printf(":\n");
    v = offsetof(, ); printf("  $%04.4lx\t%5.5ld  uop_\n",v,v);
    v = sizeof(); printf("  $%04.4lx\t%5.5ld  \n",v,v);
    */
}
